name: trackontraktfltr
description: TrackOnTrakt in flutter, jaj!

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  oauth2: ^1.2.0
  url_launcher: ^3.0.0
  shared_preferences: ^0.4.1
  flutter_webview_plugin: ^0.1.5
  json_annotation: ^0.2.4
  intl: 0.15.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^0.5.2
  build_runner: ^0.8.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/ic_big.png
    - assets/images/2.0x/ic_big.png
    - assets/images/3.0x/ic_big.png
    - assets/fonts/RobotoSlab-Bold.ttf
    - assets/fonts/RobotoSlab-Light.ttf
    - assets/fonts/RobotoSlab-Regular.ttf
    - assets/fonts/RobotoSlab-Thin.ttf
    - assets/trakt_keys.json

  fonts:
     - family: Roboto-Slab
       fonts:
         - asset: assets/fonts/RobotoSlab-Regular.ttf
         - asset: assets/fonts/RobotoSlab-Light.ttf
           weight: 100
         - asset: assets/fonts/RobotoSlab-Bold.ttf
           weight: 700

